export const UPDATE_DATASET = 'UPDATE_DATASET';
export type UPDATE_DATASET = typeof UPDATE_DATASET;

export const UPDATE_PLOT_SELECTION = 'UPDATE_PLOT_SELECTION';
export type UPDATE_PLOT_SELECTION = typeof UPDATE_PLOT_SELECTION;